spring:
   application:
      name: microservice-api-gateway
server:
   port: 8050
eureka:
#instance:
#   hostname: gateway
   instance:
      preferIpAddress: true
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
zuul:
   # 表示启用限流策略，并且所有服务在3秒内只能有1次请求且所有请求时间总和不得超过2秒
   ratelimit:
      enabled: true
      default-policy:
         limit: 1
         quota: 2
         refresh-interval: 3
   ignored-services: microservice-provider-user # 需要忽视的服务(配置后将不会被路由)
   routes:
      #movie: # 可以随便写，在zuul上面唯一即可；当这里的值=service-id时，service-id可以不写。
      #path: /movie/** # 想要映射到的路径
      #service-id: microservice-consumer-movie-ribbon-with-hystrix # Eureka中的serviceId
      api-a:
         path: /api-a/**
         serviceId: microservice-consumer-movie-ribbon-with-hystrix
      api-b:
         path: /api-b/**
         serviceId: microservice-consumer-movie-feign-with-hystrix
      api-c:
         path: /api-c/**
         serviceId: microservice-consumer-movie-ribbon
      api-d:
         path: /api-d/**
         serviceId: microservice-consumer-movie-feign
management:
   endpoints:
      web:
         exposure:
            include: '*'