server:
   port: 8040
spring:
   application:
      name: microservice-config-server
   cloud:
      config:
         server:
            git:
               # 如果是公开仓库，可以不用填写账号和密码
               uri: https://github.com/hemin1003/spring-cloud-study # 配置git仓库的地址
               search-paths: config-repo # git仓库地址下的相对地址，可以配置多个，用,分割。
               username:  # git仓库的账号
               password:  # git仓库的密码