server:
   port: 8051
management:
   endpoint:
      refresh:
         enabled: true
   endpoints:
      web:
         exposure:
            include:
            - info
            - health
            - refresh