// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: info.proto

package com.example.kafka.helloworld;

public final class HelloWorldProto {
  private HelloWorldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_HelloReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_KafkaEventOne_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_KafkaEventOne_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_KafkaEventTwo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_KafkaEventTwo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_Callback_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_Callback_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\ninfo.proto\022\nhelloworld\"\034\n\014HelloRequest" +
      "\022\014\n\004name\030\001 \001(\t\"\035\n\nHelloReply\022\017\n\007message\030" +
      "\001 \001(\t\" \n\rKafkaEventOne\022\017\n\007address\030\001 \001(\t\"" +
      "\037\n\rKafkaEventTwo\022\016\n\006number\030\001 \001(\004\"x\n\010Call" +
      "back\022.\n\tone_event\030\001 \001(\0132\031.helloworld.Kaf" +
      "kaEventOneH\000\022.\n\ttwo_event\030\002 \001(\0132\031.hellow" +
      "orld.KafkaEventTwoH\000B\014\n\nevent_type2I\n\007Gr" +
      "eeter\022>\n\010SayHello\022\030.helloworld.HelloRequ" +
      "est\032\026.helloworld.HelloReply\"\000B1\n\034com.exa" +
      "mple.kafka.helloworldB\017HelloWorldProtoP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_helloworld_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helloworld_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_HelloRequest_descriptor,
        new String[] { "Name", });
    internal_static_helloworld_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helloworld_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_HelloReply_descriptor,
        new String[] { "Message", });
    internal_static_helloworld_KafkaEventOne_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_helloworld_KafkaEventOne_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_KafkaEventOne_descriptor,
        new String[] { "Address", });
    internal_static_helloworld_KafkaEventTwo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_helloworld_KafkaEventTwo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_KafkaEventTwo_descriptor,
        new String[] { "Number", });
    internal_static_helloworld_Callback_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_helloworld_Callback_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_Callback_descriptor,
        new String[] { "OneEvent", "TwoEvent", "EventType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
