// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: info.proto

package com.example.kafka.helloworld;

public interface KafkaEventTwoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.KafkaEventTwo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 number = 1;</code>
   */
  long getNumber();
}
