// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: info.proto

package com.example.kafka.helloworld;

public interface KafkaEventOneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.KafkaEventOne)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string address = 1;</code>
   */
  String getAddress();
  /**
   * <code>string address = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
