spring:
  application:
    name: service
server:
  port: 30010
eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone01
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    region: chengdu
    availability-zones:
      chengdu: zone01,zone02
    service-url:
      zone01: http://localhost:30000/eureka/
      zone02: http://localhost:30001/eureka/
