# 应用名称
#spring.application.name=book-serivice-ribbon
# 应用服务 WEB 访问端口
#server.port=8080

server:
  port: 9000
spring:
  application:
    name: book-service-ribbon

eureka:
  instance:
    ip-address: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:1111/eureka/



