server:
   port: 8050
spring:
   application:
      name: microservice-config-server-eureka
   cloud:
      config:
         server:
            git:
               uri: https://github.com/hemin1003/spring-cloud-study
               search-paths: config-repo
               username: 
               password: 
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/